global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:578'
  smtp_from: 'maurice.chen@mitac.com.tw'
  smtp_auth_username: 'maurice.chen@mitac.com.tw'
  smtp_auth_password: 'password'
  smtp_require_tls: false

route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  group_by: ['alertname']

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']
  
receivers:
- name: 'default'
  email_configs:
  - to: 'receiver@163.com'
    send_resolved: true
  webhook_configs:
  - url: 'http://dingtalk:8060/dingtalk/webhook/send'
    send_resolved: true
